# Configuration for R2L implementations and data lakes
implementation:
  name: xmode  # Name of the implementation to use
  config:
    # ReSP-specific configuration
    openai_api_key: !env OPENAI_API_KEY  # Will be replaced with environment variable
    langchain_api_key: !env LANGCHAIN_API_KEY
    # embedding_model: "sentence-transformers/all-mpnet-base-v2"
    # max_chunks: 100
    # chunk_size: 1000
    # overlap: 200
    batch_size: 32
    # Optional: Use existing index
    index_path: "data/index"
    # Or index new data
    # Use both datasets: pubmed targets and drugbank tables
    data_path: "data/Pharma"  # This will include both pubmed-targets and drugbank-tables
    # ReSP-specific settings
    max_iterations: 5  # Maximum number of recursive iterations

data_lake:
  name: Pharma  # Name of the data lake to use
  config:
    # Data lake specific configuration
    data_path: "data/Pharma"
    # file_types: ["txt", "pdf", "md"]
    # exclude_patterns: [".*\\.git.*", ".*\\.DS_Store"]

# Global settings
# logging:
#   level: INFO
#   file: "logs/r2l.log" 